disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - force_cast
  - function_parameter_count

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - AliceX/Libary

force_try:
  severity: warning # explicitly

identifier_name:
  min_length: 2
